# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: ON_DEMAND
    instanceTypes: t3.large 
    spot: false
    desiredCapacity: 2