# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: ON-DEMAND
    instanceType: t3.medium 
    spot: false
    desiredCapacity: 2